package dictionary.gui;

import java.util.Random;
import java.awt.Color;
import javax.swing.JOptionPane;

public class PrzegrywacCzasemToNormalnaRzecz extends javax.swing.JFrame {

    String[] przegrywacLyrics = {"Czasem", "myślę", "że", "mi", "szczęścia", "brak\n", "Wszystko", "jakoś", "się", "układa", "wspak\n", "Życie", "obok", "ciągle", "mija", "mnie\n", "Jakby", "dziwną", "prowadziło", "grę\n", "Inni", "głową", "dotykają", "chmur\n", "Mają", "jakiś", "patent", "jakiś", "wzór\n", "Albo", "z", "nieba", "usłyszeli", "głos\n", "To", "wystarczy", "im", "na", "piękny", "los\n", "Coś", "było", "wiem\n", "Spóźniłem", "się\n", "Gdzieś", "czekał", "ktoś\n", "Nie", "ma", "go\n", "Przegrywać", "czasem", "to", "normalna", "rzecz\n", "Upadać", "nisko", "by", "się", "wyżej", "wznieść\n", "I", "czasem", "gdy", "zaboli", "cię", "nie", "wstydzić", "się", "swych", "własnych", "łez\n", "To", "także", "zwykła", "to", "normalna", "rzecz\n", "Wciąż", "się", "zrywa", "cienka", "krucha", "nic\n", "Ludzie", "mówią", "swoją", "szanse", "chwyć\n", "Więc", "na", "oślep", "znowu", "rzucam", "się\n", "Tylko", "pustkę", "tak", "jak", "zawsze", "tnę\n", "Coś", "było", "wiem\n", "Spóźniłem", "się\n", "Gdzieś", "czekał", "ktoś", "Nie", "ma", "go\n"};
    
    String[] amendedPrzegrywac = new String[113];
    String[] checkKek = new String[113];
    int selected = 0;
    int corrAns = 0;
     int task = 0;
            
    public PrzegrywacCzasemToNormalnaRzecz() {
        initComponents();
         setLocationRelativeTo(null);
        showLyrics();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_start = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_lyrics = new javax.swing.JTextArea();
        lb_missing = new javax.swing.JLabel();
        tf_answer = new javax.swing.JTextField();
        bt_check = new javax.swing.JButton();
        lb_corrans = new javax.swing.JLabel();
        lb_counter = new javax.swing.JLabel();
        lb_correct = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Przegrywać czasem to normalna rzecz...");

        bt_start.setText("START");
        bt_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_startActionPerformed(evt);
            }
        });

        ta_lyrics.setColumns(20);
        ta_lyrics.setRows(5);
        jScrollPane1.setViewportView(ta_lyrics);

        lb_missing.setText("Missing word:");

        bt_check.setText("CHECK");
        bt_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_checkActionPerformed(evt);
            }
        });

        lb_corrans.setText("Correct answers:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_missing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_answer, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_corrans, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_counter, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_correct, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(189, 189, 189)
                                .addComponent(bt_check))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(bt_start)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_start)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_missing)
                    .addComponent(tf_answer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(lb_correct, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_check)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_counter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_corrans, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_startActionPerformed
        lb_correct.setText("");
        tf_answer.setBackground(Color.WHITE);
        tf_answer.setText("");
        task++;
        editLyrics();
    }//GEN-LAST:event_bt_startActionPerformed

    private void bt_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_checkActionPerformed
        String lowCase = przegrywacLyrics[selected].strip().toLowerCase();
        if (tf_answer.getText().equals(lowCase)) {
            tf_answer.setBackground(Color.GREEN);
            corrAns++;
        } else {
            tf_answer.setBackground(Color.RED);
            lb_correct.setText(przegrywacLyrics[selected]);
        }
        lb_counter.setText(corrAns + "/" + task + ", " + corrAns * 100 / task + "%");

        if (task == 5) {
            JOptionPane.showInternalMessageDialog(null, "Your result is: " + corrAns + " correct answer out of " + (task) + ". Percentage:" + corrAns * 100 / (task) + "%!", "GAME OVER!", JOptionPane.INFORMATION_MESSAGE);
            dispose();
            new Start().setVisible(true);
        }
    }//GEN-LAST:event_bt_checkActionPerformed

    private void showLyrics() {
        String text = "";

        for (String word : przegrywacLyrics) {
            text += word + " ";
        }
        ta_lyrics.setText(text);
        ta_lyrics.setEditable(false);
    }

    private void editLyrics() {
        Random random = new Random();
        int maxRandom = przegrywacLyrics.length;
        selected = random.nextInt(maxRandom - 1) + 1;

        StringBuilder empty = new StringBuilder();
        StringBuilder newText = new StringBuilder();
        String emptyString = "";

        for (int i = 0; i < przegrywacLyrics.length; i++) {
            if (przegrywacLyrics[i].equals(przegrywacLyrics[selected])) {
                for (int j = 0; j < przegrywacLyrics[i].length(); j++) {
                    empty.append("_");
                }
                emptyString = empty.toString();
                amendedPrzegrywac[i] = emptyString;
            } else {
                amendedPrzegrywac[i] = przegrywacLyrics[i];
            }
        }
        for (String string : amendedPrzegrywac) {
            newText.append(string + " ");
        }
        ta_lyrics.setText(newText.toString());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrzegrywacCzasemToNormalnaRzecz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrzegrywacCzasemToNormalnaRzecz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrzegrywacCzasemToNormalnaRzecz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrzegrywacCzasemToNormalnaRzecz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrzegrywacCzasemToNormalnaRzecz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_check;
    private javax.swing.JButton bt_start;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_corrans;
    private javax.swing.JLabel lb_correct;
    private javax.swing.JLabel lb_counter;
    private javax.swing.JLabel lb_missing;
    private javax.swing.JTextArea ta_lyrics;
    private javax.swing.JTextField tf_answer;
    // End of variables declaration//GEN-END:variables
}
